library(tidyverse)
library(dplyr)
library(ggplot2)
library(scales)
library(stringr)

# The functions might be useful for A4
source("~/info201/assignments/a4-JahMeat/source/a4-helpers.R")

# Get Dataset:

incarceration_df <- get_data()
View(incarceration_df)

## Section 2  ---- 
#----------------------------------------------------------------------------#
# Data Summary
#----------------------------------------------------------------------------#

# What is the average proportion of black incarceration population across
# all urbanicities? 

urbanicity_black_proportion <- incarceration_df %>% 
  group_by(urbanicity) %>% 
  summarize(black = mean(black_jail_pop, na.rm = TRUE), 
            total = mean(total_jail_pop, na.rm = TRUE)) %>% 
  filter(is.nan(black) == FALSE & is.nan(total) == FALSE) %>% 
  summarize(proportion = mean(black / total)) %>% 
  pull(proportion)

# Which state has the highest proportion of incarceration in the most
# populated region?

most_populated_region <- incarceration_df %>% 
  group_by(region) %>% 
  summarize(population = sum(total_pop)) %>% 
  filter(population == max(population)) %>% 
  pull(region)

region_state_proportion <- incarceration_df %>% 
  filter(state %in% states_in_region(most_populated_region)) %>% 
  filter(!state %in% states_with_no_jail_pop()) %>% 
  group_by(state) %>% 
  summarize(pop = sum(total_pop), jail = sum(total_jail_pop, na.rm = TRUE)) %>% 
  mutate(proportion = jail / pop) %>% 
  filter(proportion == max(proportion)) %>% 
  pull(state)

# Which year has the highest incarceration population?

highest_incarceration_year <- incarceration_df %>% 
  group_by(year) %>% 
  summarize(incarceration = sum(total_jail_pop, na.rm = TRUE)) %>% 
  filter(incarceration == max(incarceration)) %>% 
  pull(year)

## Section 3  ---- 
#----------------------------------------------------------------------------#
# Growth of the U.S. Prison Population
# Your functions might go here ... <todo:  update comment>
#----------------------------------------------------------------------------#
# This function summarizes the total prison population for each year
# in a dataframe. 
get_year_jail_pop <- function() {
  df <- incarceration_df %>% 
    group_by(year) %>% 
    summarize(pop = sum(total_jail_pop, na.rm = TRUE)) %>% 
return(df)   
}

# This function creates a bar chart based on the dataframe generated
# by the above function. 
plot_jail_pop_for_us <- function()  {
  plot <- ggplot(data = get_year_jail_pop()) +
    geom_col(
      mapping = aes(x = year, y = pop),
      color = "white"
    ) +
    scale_y_continuous(label = comma_format(big.mark = ",")) +
    labs(
      title = "U.S. Prison Population 1970 to 2018",
      caption = "A bar chart that outlines the trend of prison population in the U.S. from 1970 to 2018",
      x = "Year",
      y = "Incarcerations"
    )
  return(plot)   
} 

## Section 4  ---- 
#----------------------------------------------------------------------------#
# Growth of Prison Population by State 
#----------------------------------------------------------------------------#
# This function extracts a dataframe that records the prison population for 
# parameterized states for each recorded year. 
get_jail_pop_by_states <- function(states) {
  df <- incarceration_df %>% 
    filter(state %in% states) %>% 
    group_by(year, state) %>% 
    summarize(pop = sum(total_jail_pop, na.rm = TRUE))
  return(df)
}

# This function creates a line chart based on the dataframe generated by the
# above function and allows the same input for parameterized states. 
plot_jail_pop_by_states <- function(states) {
  plot <- ggplot(
    data = get_jail_pop_by_states(states),
    mapping = aes(x = year, y = pop, color = state)
  ) +
    geom_line() +
    scale_y_continuous(label = comma_format(big.mark = ",")) +
    labs(
      title = "Prison Population by State 1970 to 2018",
      caption = "A line chart that outlines the trend of prison population for 7 geographically apart states from 1970 to 2018",
      x = "Year",
      y = "Incarcerations",
    )
  return(plot)
}

## Section 5  ---- 
#----------------------------------------------------------------------------#
# Proportion of Blacks in Jail by Region
#----------------------------------------------------------------------------#
# This function generates a dataframe that summarizes black population in jail
# and total jail population for each region.
get_black_proportion_by_region <- function() {
  df <- incarceration_df %>% 
    group_by(region) %>% 
    summarize(black = black_jail_pop, total = total_jail_pop) %>% 
    return(df)
}

# This function creates a scatterplot matrix by including facets for each region
# and generating comparison of population for the function above. 
plot_black_proportion_by_region <- function() {
  plot <- ggplot(data = get_black_proportion_by_region(),
                 mapping = aes(x = total, y = black)
                 ) +
          geom_point(alpha = .5, color = "green") +
          geom_smooth(color = "red") +
          facet_wrap(~region) +
    labs(
      title = "Black Population vs. Total Population in Prison by Region",
      caption = "A scatterplot matrix of comparison between black population
      in prison and total population in prison to generate black proportions in
      prison for each region of U.S.",
      x = "Total Population of Incarceration",
      y = "Black Population of Incarceration"
    )
  return(plot)
}
## Section 6  ---- 
#----------------------------------------------------------------------------#
# Proportion of Incarcerated Blacks for every County in Washington
#----------------------------------------------------------------------------#

str <- str_remove(incarceration_df$county_name, " County")
str <- tolower(str)
get_pop_race_per_county <- function() {
  df <- incarceration_df %>%
    mutate(county_name = str) %>% 
    filter(state == "WA") %>% 
    group_by(county_name) %>% 
    summarize(prison = sum(black_jail_pop, na.rm = TRUE), 
              normal = sum(black_pop_15to64, na.rm = TRUE)
              ) %>% 
    mutate(proportion = prison / normal)
  return(df)
}

plot_pop_race_per_county <- function() {
  plot <- map_data("county") %>% 
    filter(region == "washington") %>% 
    rename(county_name = subregion) %>% 
    left_join(get_pop_race_per_county(), by = "county_name")
  
  plot <- ggplot(data = plot) +
    geom_polygon(
      mapping = aes(x = long, y = lat, group = group, fill = proportion),
      color = "white",
      size = .1
    ) + 
    coord_map() +
    scale_fill_continuous(low = "black", high = "purple") +
    labs(
      title = "Proportion of Incarcerated Blacks for every County in Washington",
      caption = "A choropleth map of Washington state portraying the proportion of black population
      that are serving in prison for each county.",
      fill = "Proportion"
      ) +
    theme_bw() +
    theme(
      axis.line = element_blank(),
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
    )
  return(plot)
}

## Load data frame ---- 


